### ISSUE TITLE
Search by name not working and Plugin crash

### ISSUE THREAD

**Issue by DarklDrift** [nesrak1/UABEA#32] opened 2021-05-11 15:24 UTC
Hi! I found two mayor issues with the program. First when i click on the Search by name button nothing happens. Second is the with the plugins button. When i click on the plugins button the UABEA stop working and then a crash.
SECOND RELEASE

**Comment by nesrak1** [comment] 2021-05-11 15:37
> First when i click on the Search by name button nothing happens.

Searching is not implemented yet so it doesn't do anything right now.

> When i click on the plugins button the UABEA stop working and then a crash.

Can you please post a [stack trace](https://github.com/nesrak1/UABEA/issues/15#issuecomment-826471729)?

**Comment by nesrak1** [comment] 2021-05-11 19:25
I need the .NET Runtime error, not the Application error.

**Comment by HyperSnip3r** [comment] 2021-05-12 00:40
Nesrak1 Is it ok with you if I make a Youtube video showing how to make Among Us hats with your UABE ?

**Comment by nesrak1** [comment] 2021-05-12 00:53
Yes

**Comment by DarklDrift** [comment] 2021-05-12 14:04
yes

**Comment by nesrak1** [comment] 2021-05-13 03:29
The error seems to suggest there was no asset selected, but try the [latest build](https://nightly.link/nesrak1/UABEA/workflows/dotnet-desktop/master/uabea-windows.zip) anyway to see what happens.

**Comment by nesrak1** [comment] 2021-05-16 17:42
Can't reproduce the crash, so I'm closing this issue. Reopen this if you still have issues.

**Closed by nesrak1** 2021-05-16 17:42 UTC
Labels: bug, feature
