### ISSUE TITLE
Mod Maker Feature - Standalone installer needed.

### ISSUE THREAD

**Issue by M-Elisabeth** [nesrak1/UABEA#121] opened 2021-11-03 20:01 UTC
It doesn't work for some reason.
I try to mod Darkest Dungeon 2 and UABEA is the only tool that allows me to mod the game (for now).
It was Godsend, but without the installer feature, I've to force everyone who wants to use my mod to replace the whole asset file just to see a change for a single 2D texture.

This brings up compatibility issues, it can't show more than one mod and is forced to replace each other out, rather discouraging people who want to jump into the modding scene. I also have to sacrifice my previous mod for a future mod that changes entirely different texture2D.

Is it possible to fix this?

**Comment by nesrak1** [comment] 2021-11-03 21:05
Duplicate of #86. You can mod assets files for the time being and install them through command line as explained in that issue. Bundles can't be modded due to a bug in the AssetsTools.NET library which will be fixed when I have time to review the pull request. As for why the standalone installer isn't supported, I'd at least want to find a cross platform solution for installing (and newer versions of .NET are hard to package in one executable file).

**Closed by nesrak1** 2021-11-03 21:05 UTC
