### ISSUE TITLE
Crashing on large files

### ISSUE THREAD

**Issue by daniandl** [nesrak1/UABEA#35] opened 2021-05-14 12:09 UTC
Hey there, first of all, thanks so much for doing this.

On large files (150MB+), the program sadly just closes after ~5 seconds of loading.
I'm testing this out with the game Rust at the moment, to extract sounds, so I can add them to my video project :P  

Here is the `audio` bundle file from the game: https://we.tl/t-IgtlSgKdpH

Any help here is appreciated :)

**Comment by nesrak1** [comment] 2021-05-14 16:20
I tested your file and it was able to open both in the second release and the latest build. Does it crash when clicking the info button or when initially opening the file?

Also there's no audio export plugin yet, so I would suggest using AssetStudio to get audio.

**Comment by nesrak1** [comment] 2021-05-16 17:42
Can't reproduce the crash, so I'm closing this issue. Reopen this if you still have issues.

**Closed by nesrak1** 2021-05-16 17:42 UTC
Labels: bug
