### ISSUE TITLE
Scene Hierarchy 'PARTIAL SEARCH'

### ISSUE THREAD

**Issue by amdvce** [nesrak1/UABEA#292] opened 2023-11-22 04:13 UTC
**Is your feature request related to a problem? Please describe.**
Scene Hierarchy 'PARTIAL SEARCH'

**Describe the solution you'd like**
Some unity have very large game objects and without an SEARCH in "Scene Hierarchy" the tool UABEA is incomplete !
A very useful option will be implementing a SEARCH capability including the most important "PARTIAL SEARCH" and not searching by full name as searching only by full name will again be a mistake and useless as I DO NOT KNOW THE FULL NAME in the (Asset Info -> View -> Search by name)  !

**Additional context**
Resuming an complementary useful options will be implementing **PARTIAL** NAME SEARCH in both "Scene Hierarchy" &  (Asset Info -> View -> Search by name)

**Comment by nesrak1** [comment] 2023-11-22 16:17
The asset info list has partial search if you use wildcards. Surround your search term with `*` like `*thing I want to search*`

**Comment by amdvce** [comment] 2023-11-23 10:23
It's all right, i found something else besides UABEA.
I use now https://github.com/Polarmods/DevX-Cracked that has search trough hierarchy. It's just wonderful.
Like https://github.com/aelurum/AssetStudio too has search trough hierarchy.
Both shows the search in realtime.

Unfortunate UABEA is incomplete for me and very hard to work with on/with unity with large gameobject's.
And since then i delete UABEA since for me it's useless.

Thanks anyway.

**Comment by nesrak1** [comment] 2023-11-23 20:38
I'm sorry that the search is not up to your standards. Your request is commonly requested and is already part of the work in progress version here: https://github.com/nesrak1/UABEANext

I think calling a slightly more difficult search "useless" is a bit harsh though.

**Comment by amdvce** [comment] 2023-11-24 10:55
![uabea is crap](https://github.com/nesrak1/UABEA/assets/145987091/31fefb85-f523-402f-bc88-741a7c97515d)
![uabea is malware](https://github.com/nesrak1/UABEA/assets/145987091/6c724df9-9a62-4c99-a9ba-a668a5394fd4)

Yours tools are bad & bad, comporting like malware, it modify the files in progfiles\dotnet subs.

I don't have time for this nonsense of yours, i am in charge over 14000 people.
If you had to work for me i had you being fired long ago.

So when i closed this as complete i expected to be complete as in my view this tools of your are a complete waste of time.
And i don't deal with malware like yours**.**

**Comment by nesrak1** [comment] 2023-11-24 17:46
UABEA is an open source project with releases binaries straight from Github actions. I don't know what you're suggesting is the "malware" but you're more than welcome to look over the code in this repo.

The reason the issue is reopened is because your request was never completed. You're closing the issue because you have an odd thing against UABEA, but that doesn't invalidate the fact that scene hierarchy searching or wildcardless search doesn't exist. The issue will be reopened until the feature is complete.

**Comment by amdvce** [comment] 2024-01-16 10:03
.

**Closed** 2024-01-16 10:04 UTC
Labels: feature
