### ISSUE TITLE
Urgent: UABEA cant open resources.assets file while AssetBundleExtractor can.

### ISSUE THREAD

**Issue by Flanua** [nesrak1/UABEA#302] opened 2024-01-29 17:40 UTC
System.ArgumentException: The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'. (Parameter 'chars')
   at System.Text.Encoding.ThrowCharsOverflow(DecoderNLS decoder, Boolean nothingDecoded)
   at System.Text.Encoding.GetCharsWithFallback(ReadOnlySpan`1 bytes, Int32 originalBytesLength, Span`1 chars, Int32 originalCharsLength, DecoderNLS decoder)
   at System.Text.UTF8Encoding.GetCharsWithFallback(ReadOnlySpan`1 bytes, Int32 originalBytesLength, Span`1 chars, Int32 originalCharsLength, DecoderNLS decoder)
   at System.Text.Encoding.GetCharsWithFallback(Byte* pOriginalBytes, Int32 originalByteCount, Char* pOriginalChars, Int32 originalCharCount, Int32 bytesConsumedSoFar, Int32 charsWrittenSoFar, DecoderNLS decoder)
   at System.Text.DecoderNLS.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, Boolean flush)
   at System.Text.Decoder.GetChars(ReadOnlySpan`1 bytes, Span`1 chars, Boolean flush)
   at System.IO.BinaryReader.Read()
   at System.IO.BinaryReader.ReadChar()
   at AssetsTools.NET.AssetsFileReader.ReadNullTerminated()
   at AssetsTools.NET.AssetsFileExternal.Read(AssetsFileReader reader)
   at AssetsTools.NET.AssetsFileMetadata.Read(AssetsFileReader reader, UInt32 version, Int64 dataOffset)
   at AssetsTools.NET.AssetsFileMetadata.Read(AssetsFileReader reader, AssetsFileHeader header)
   at AssetsTools.NET.AssetsFile.Read(AssetsFileReader reader)
   at AssetsTools.NET.Extra.AssetsFileInstance..ctor(Stream stream, String filePath)
   at AssetsTools.NET.Extra.AssetsManager.LoadAssetsFileCacheless(Stream stream, String path, Boolean loadDeps, BundleFileInstance bunInst)
   at AssetsTools.NET.Extra.AssetsManager.LoadAssetsFile(FileStream stream, Boolean loadDeps)
   at AssetsTools.NET.Extra.AssetsManager.LoadAssetsFile(String path, Boolean loadDeps)
   at UABEAvalonia.MainWindow.OpenFiles(String[] files) in D:\a\UABEA\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 111
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.JobWithArg.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 241
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 267
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 215
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 122
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 214
   at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 53

**Comment by Flanua** [comment] 2024-01-29 17:45
Need urgently open my resources.assets file to dumb mesh info in json format because json dump from AssetBundleExtractor is different and can't be imported into UABEA.

**Comment by nesrak1** [comment] 2024-01-30 13:48
Is this a free game? This would be hard to fix without a file.

**Comment by Cocollini** [comment] 2024-01-30 17:59
I am having the same problem when i try to open the sharedassets0.assets of the game Huniepop, but with others programs like AssetStudio i can, idk how to fix this :(

**Comment by nesrak1** [comment] 2024-01-31 00:40
@Cocollini Is it the same error? If not, open a new issue.

**Comment by Cocollini** [comment] 2024-01-31 02:13
> @Cocollini Is it the same error? If not, open a new issue.

yes is the same

**Comment by Flanua** [comment] 2024-01-31 20:45
> Is this a free game? This would be hard to fix without a file.

Yes its actually a free game from a steam with even a source code available the game is called: Planet Explorers

**Comment by nesrak1** [comment] 2024-02-01 00:06
Can't reproduce on any of the four `resources.assets` files in Planet Explorers. They all open fine for me. Are you on a non-English system by any chance? The exception seems to be in English but I just want to double check.

**Comment by Flanua** [comment] 2024-02-01 01:24
> Can't reproduce on any of the four `resources.assets` files in Planet Explorers. They all open fine for me. Are you on a non-English system by any chance? The exception seems to be in English but I just want to double check.

Sorry forgot to mention it can’t open older smaller build: Planet Explorers Alpha 0.53 
It can be downloaded from here:
https://www.indiedb.com/games/planet-explorers/downloads/planet-explorers-alpha-053

**Comment by nesrak1** [comment] 2024-02-01 03:58
That version's release date is 2013, which is two years before unity 5's release date. UABEA will only support unity 5 and above. So this is just a wontfix.

**Closed by nesrak1** 2024-02-01 03:58 UTC
Labels: bug
