### ISSUE TITLE
 The process was terminated due to an unhandled exception

### ISSUE THREAD

**Issue by formatingxie** [nesrak1/UABEA#17] opened 2021-04-26 09:03 UTC
日志名称:          Application
来源:            .NET Runtime
日期:            2021/4/26 15:50:47
事件 ID:         1026
任务类别:          无
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           PC-20201219HSPT
描述:
Application: UABEAvalonia.exe
CoreCLR Version: 5.0.521.16609
.NET Version: 5.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: Stream was not readable.
   at System.IO.BinaryReader..ctor(Stream input, Encoding encoding, Boolean leaveOpen)
   at AssetsTools.NET.AssetsFileReader..ctor(Stream stream) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Standard\AssetsFileFormat\AssetsFileReader.cs:line 10
   at UABEAvalonia.MainWindow.DecompressToFile(BundleFileInstance bundleInst, String savePath) in C:\Users\nesquack\source\repos\UABEAvalonia\UABEAvalonia\MainWindow.axaml.cs:line 168
   at UABEAvalonia.MainWindow.AskLoadCompressedBundle(BundleFileInstance bundleInst) in C:\Users\nesquack\source\repos\UABEAvalonia\UABEAvalonia\MainWindow.axaml.cs:line 144
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at UABEAvalonia.Program.Main(String[] args) in C:\Users\nesquack\source\repos\UABEAvalonia\UABEAvalonia\Program.cs:line 13

事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-04-26T07:50:47.916251900Z" />
    <EventRecordID>6157</EventRecordID>
    <Channel>Application</Channel>
    <Computer>PC-20201219HSPT</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: UABEAvalonia.exe
CoreCLR Version: 5.0.521.16609
.NET Version: 5.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: Stream was not readable.
   at System.IO.BinaryReader..ctor(Stream input, Encoding encoding, Boolean leaveOpen)
   at AssetsTools.NET.AssetsFileReader..ctor(Stream stream) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Standard\AssetsFileFormat\AssetsFileReader.cs:line 10
   at UABEAvalonia.MainWindow.DecompressToFile(BundleFileInstance bundleInst, String savePath) in C:\Users\nesquack\source\repos\UABEAvalonia\UABEAvalonia\MainWindow.axaml.cs:line 168
   at UABEAvalonia.MainWindow.AskLoadCompressedBundle(BundleFileInstance bundleInst) in C:\Users\nesquack\source\repos\UABEAvalonia\UABEAvalonia\MainWindow.axaml.cs:line 144
   at System.Threading.Tasks.Task.&lt;&gt;c.&lt;ThrowAsync&gt;b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.&lt;&gt;c__DisplayClass5_0.&lt;Post&gt;b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG&amp; lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at UABEAvalonia.Program.Main(String[] args) in C:\Users\nesquack\source\repos\UABEAvalonia\UABEAvalonia\Program.cs:line 13
</Data>
  </EventData>
</Event>

**Comment by nesrak1** [comment] 2021-04-26 15:10
Fixed in latest commit. A workaround with that release is to just extract the bundle to memory rather than file.

**Comment by formatingxie** [comment] 2021-04-27 01:07
nice ,thank！

**Comment by formatingxie** [comment] 2021-04-27 02:21
Hello, I've updated the latest code. This problem is still not fixed (file - > open   ：and then it gets stuck)

**Comment by nesrak1** [comment] 2021-04-27 02:25
Immediately after file->open or after opening a file and decompressing the bundle?

**Comment by formatingxie** [comment] 2021-05-10 06:20
![image](https://user-images.githubusercontent.com/4608093/117614286-b2eeb380-b19a-11eb-8f6c-aa4b16c24119.png)
The latest version is still like this. Click file - > open to get stuck

**Comment by formatingxie** [comment] 2021-05-11 06:10
日志名称:          Application
来源:            Application Hang
日期:            2021/5/11 14:14:13
事件 ID:         1002
任务类别:          (101)
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           PC-20201219HSPT
描述:
程序 UABEAvalonia.exe 版本 1.0.0.0 已停止与 Windows 交互并关闭。若要查看是否有关于该问题的详细信息，请检查“安全性与维护”控制面板中的问题历史记录。
 进程 ID: 22a0
 开始时间: 01d7462cc790d264
 终止时间: 6
 应用程序路径: G:\project\A_TOOL\uabea_rel2_win_x64\UABEAvalonia.exe
 报告 ID: 538739a0-ec7f-477f-81a2-00bd1c6058f8
 错误程序包全名: 
 错误程序包相关应用程序 ID: 
 挂起类型: Cross-thread

事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Hang" />
    <EventID Qualifiers="0">1002</EventID>
    <Level>2</Level>
    <Task>101</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-05-11T06:14:13.922124500Z" />
    <EventRecordID>7708</EventRecordID>
    <Channel>Application</Channel>
    <Computer>PC-20201219HSPT</Computer>
    <Security />
  </System>
  <EventData>
    <Data>UABEAvalonia.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>22a0</Data>
    <Data>01d7462cc790d264</Data>
    <Data>6</Data>
    <Data>G:\project\A_TOOL\uabea_rel2_win_x64\UABEAvalonia.exe</Data>
    <Data>538739a0-ec7f-477f-81a2-00bd1c6058f8</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>Cross-thread</Data>
    <Binary>430072006F00730073002D00740068007200650061006400000044006500610064006C006F0063006B0000000000</Binary>
  </EventData>
</Event>

**Comment by formatingxie** [comment] 2021-05-11 06:11
日志名称:          Application
来源:            Windows Error Reporting
日期:            2021/5/11 14:14:13
事件 ID:         1001
任务类别:          无
级别:            信息
关键字:           经典
用户:            暂缺
计算机:           PC-20201219HSPT
描述:
故障存储段 1425640499636892669，类型 5
事件名称: AppHangB1
响应: 不可用
Cab ID: 0

问题签名:
P1: UABEAvalonia.exe
P2: 1.0.0.0
P3: 5fd43c92
P4: 8dc5
P5: 134218252
P6: 
P7: 
P8: 
P9: 
P10: 

附加文件:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER994C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER996C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER996B.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER997C.tmp.txt
\\?\C:\Users\Administrator\AppData\Local\Temp\WER9FF5.tmp.appcompat.txt

可在此处获取这些文件:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_UABEAvalonia.exe_82b232db3124cef5455dc8783895a558dbd965_99620cb2_b21fd46a-7625-4b80-ac4c-e9b67d6ea269

分析符号: 
重新检查解决方案: 0
报告 ID: 538739a0-ec7f-477f-81a2-00bd1c6058f8
报告状态: 268435456
哈希存储段: 4f9be23a66e337e8c3c8e47b264473fdnCab GUID: 0
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-05-11T06:14:13.649432400Z" />
    <EventRecordID>7707</EventRecordID>
    <Channel>Application</Channel>
    <Computer>PC-20201219HSPT</Computer>
    <Security />
  </System>
  <EventData>
    <Data>1425640499636892669</Data>
    <Data>5</Data>
    <Data>AppHangB1</Data>
    <Data>不可用</Data>
    <Data>0</Data>
    <Data>UABEAvalonia.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>5fd43c92</Data>
    <Data>8dc5</Data>
    <Data>134218252</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER994C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER996C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER996B.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER997C.tmp.txt
\\?\C:\Users\Administrator\AppData\Local\Temp\WER9FF5.tmp.appcompat.txt</Data>
    <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_UABEAvalonia.exe_82b232db3124cef5455dc8783895a558dbd965_99620cb2_b21fd46a-7625-4b80-ac4c-e9b67d6ea269</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>538739a0-ec7f-477f-81a2-00bd1c6058f8</Data>
    <Data>268435456</Data>
    <Data>4f9be23a66e337e8c3c8e47b264473fd</Data>
    <Data>0</Data>
  </EventData>
</Event>

**Comment by nesrak1** [comment] 2021-05-11 06:20
Are there any .net exceptions or just these?

**Comment by formatingxie** [comment] 2021-05-11 08:13
![image](https://user-images.githubusercontent.com/4608093/117781873-a8541d00-b273-11eb-8b53-8fe76259ffec.png)
. net is installed

**Comment by nesrak1** [comment] 2021-05-11 15:32
No I meant are there any logs that start with .NET Runtime like the first one you posted:
```
日志名称: Application
来源: .NET Runtime
```
The last two you posted are Windows Error Reporting and Application Hang which is not what I need.

**Comment by nesrak1** [comment] 2021-05-16 17:45
Can't reproduce the crash, so I'm closing this issue. Reopen this if you still have issues.

**Closed by nesrak1** 2021-05-16 17:45 UTC
Labels: bug

**Comment by formatingxie** [comment] 2021-06-09 07:08
Description: A .NET application failed.
Application: UABEAvalonia.exe
Path: D:\uabea_rel2_win_x64 (1)\UABEAvalonia.exe
Message: A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [D:\uabea_rel2_win_x64 (1)\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].

The .NET runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=5.0.2
![image](https://user-images.githubusercontent.com/4608093/121309091-5961dc00-c934-11eb-8b89-9b4779dbf761.png)
