### ISSUE TITLE
Are you planning to add the function Standalone .exe creator soon?

### ISSUE THREAD

**Issue by Cossmoss1** [nesrak1/UABEA#118] opened 2021-10-30 14:58 UTC

**Comment by nesrak1** [comment] 2021-11-02 00:28
Duplicate of #86.

**Closed by nesrak1** 2021-11-02 00:28 UTC

**Comment by Cossmoss1** [comment] 2021-11-09 17:17
I see that i can install the mods with emip files i just need to know how to do that with the command file

Can you explain to me how to do that  or link me a youtube video on how to do that process?

i never used command lines before
